config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :departments
  resources :employees
  root to: "employees#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
# frozen_string_literal: true

class Department < ApplicationRecord
  paginates_per 10

  has_many :employees, dependent: :destroy

  validates :name, presence: true
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  paginates_per 10

  belongs_to :department

  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
# frozen_string_literal: true

class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_department, only: %i[show edit update destroy]

  def index
    @departments = Department.all.page params[:page]
  end

  def new
    @department = Department.new
  end

  def edit; end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render 'new'
    end
  end

  def update
    if @department.update(department_params)
      redirect_to departments_path
    else
      render 'edit'
    end
  end

  def destroy
    @department.destroy

    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end

  def find_department
    @department = Department.find(params[:id])
  end
end

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_employee, only: %i[show edit update destroy]

  def index
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true).page params[:page]
  end

  def new
    @employee = Employee.new
  end

  def edit; end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path
    else
      render 'new'
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy

    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :department_id, :active)
  end

  def find_employee
    @employee = Employee.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/departments/_form.html.erb
<% if @department.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= 'Errors:' %></h5>
    <ul>
      <% @department.errors.messages.each  do |attr, msg| %>
        <li><%= msg.to_s.gsub(/\["|"\]/, '') %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="container col-xl-8 col-lg-12  col-md-12 col-xs-1">
  <%= form_for @department do |f| %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', placeholder: 'name' %><br>
    </div>
    <div class="form-group">
      <%= f.submit 'Save', class:'btn btn-info'%>
    </div>

  <% end %>
  <p><%= link_to 'Back', departments_path, class:'btn btn-primary' %></p>
</div>

app/views/departments/edit.html.erb
<%= render 'form' %>

app/views/departments/index.html.erb
<%= link_to 'Create new', new_department_path %>
<table class="table">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">Name</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @departments.each do |department| %>
    <tr>
      <th scope="row"><%= department.id %></th>
      <th scope="row"><%= department.name %></th>
      <th scope="row">
        <%= link_to 'Edit', edit_department_path(department) %> |
        <%= link_to 'Delete', department_path(department), method: :delete %>
      </th>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @departments %>

app/views/departments/new.html.erb
<%= render 'form' %>

app/views/employees/_form.html.erb
<% if @employee.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= 'Errors:' %></h5>
    <ul>
      <% @employee.errors.messages.each  do |attr, msg| %>
        <li><%= msg.to_s.gsub(/\["|"\]/, '') %></li>
      <%end%>
    </ul>
  </div>
<% end %>

<div class="container col-xl-8 col-lg-12  col-md-12 col-xs-1">
  <%= form_for @employee do |f| %>
    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: 'form-control', placeholder: 'name' %><br>
    </div>
    <div class="form-group">
      <%= f.label :department %><br>
      <%= f.collection_select :department_id, Department.order(:name), :id, :name, {include_blank: true}, class: 'form-control' %><br>
    </div>
    <div class="form-group">
      <%= f.label :active %><br>
      <%= f.check_box :active %><br>
    </div>
    <div class="form-group">
      <%= f.submit 'Save', class:'btn btn-info'%>
    </div>

  <% end %>
  <p><%= link_to 'Back', employees_path, class:'btn btn-primary' %></p>
</div>

app/views/employees/edit.html.erb
<%= render 'form' %>

app/views/employees/index.html.erb
<%= link_to 'Create new', new_employee_path %>
<%= search_form_for @q do |f| %>
  <%= f.label :name_cont, 'Name start with' %>
  <%= f.search_field :name_cont %>
  <%= f.submit %>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">Name</th>
    <th scope="col">Active</th>
    <th scope="col">Department</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <th scope="row"><%= employee.id %></th>
        <th scope="row"><%= employee.name %></th>
        <th scope="row"><%= employee.active %></th>
        <th scope="row"><%= employee.department.name %></th>
        <th scope="row">
          <%= link_to 'Edit', edit_employee_path(employee) %> |
          <%= link_to 'Delete', employee_path(employee), method: :delete %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @employees %>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'Employees', employees_path %>
  <%= link_to 'Departments', departments_path %>
  <form class="form-inline">
    <%= link_to 'Log out', destroy_user_session_path %>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>